-- Replace template-driven media prompting with a DB-backed OpenAI optimizer.

CREATE TABLE IF NOT EXISTS public.image_prompt_optimizer_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL,
  version TEXT NOT NULL,
  name TEXT NOT NULL,
  provider TEXT NOT NULL DEFAULT 'openai',
  model TEXT NOT NULL,
  max_completion_tokens INTEGER NOT NULL DEFAULT 500,
  system_prompt TEXT NOT NULL,
  user_prompt_template TEXT NOT NULL,
  settings JSONB NOT NULL DEFAULT '{}'::jsonb,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS image_prompt_optimizer_configs_key_version_idx
  ON public.image_prompt_optimizer_configs (key, version);

DROP INDEX IF EXISTS public.image_prompt_optimizer_configs_active_key_idx;
CREATE UNIQUE INDEX image_prompt_optimizer_configs_active_key_idx
  ON public.image_prompt_optimizer_configs (key)
  WHERE active = true;

CREATE TABLE IF NOT EXISTS public.image_prompt_generations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  story_id BIGINT,
  source TEXT NOT NULL,
  optimizer_config_id BIGINT,
  optimizer_key TEXT NOT NULL,
  optimizer_version TEXT NOT NULL,
  optimizer_provider TEXT NOT NULL,
  optimizer_model TEXT NOT NULL,
  optimizer_input JSONB NOT NULL DEFAULT '{}'::jsonb,
  optimized_prompt TEXT,
  status TEXT NOT NULL,
  latency_ms INTEGER,
  error_text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS image_prompt_generations_story_created_idx
  ON public.image_prompt_generations (story_id, created_at DESC);

CREATE INDEX IF NOT EXISTS image_prompt_generations_optimizer_created_idx
  ON public.image_prompt_generations (optimizer_config_id, created_at DESC);

ALTER TABLE public.story_media
  ADD COLUMN IF NOT EXISTS image_prompt_generation_id BIGINT,
  ADD COLUMN IF NOT EXISTS optimizer_config_id BIGINT;

ALTER TABLE public.prompt_run_events
  ADD COLUMN IF NOT EXISTS prompt_version TEXT,
  ADD COLUMN IF NOT EXISTS optimizer_config_id BIGINT;

ALTER TABLE public.story_media
  DROP COLUMN IF EXISTS prompt_template_id;

ALTER TABLE public.published_feed_entries
  DROP COLUMN IF EXISTS prompt_template_id,
  DROP COLUMN IF EXISTS prompt_template_name;

ALTER TABLE public.prompt_run_events
  DROP COLUMN IF EXISTS prompt_template_id;

DROP INDEX IF EXISTS public.story_media_prompt_template_idx;

DROP TABLE IF EXISTS public.prompt_templates;

INSERT INTO public.image_prompt_optimizer_configs (
  key,
  version,
  name,
  provider,
  model,
  max_completion_tokens,
  system_prompt,
  user_prompt_template,
  settings,
  active,
  updated_at
)
VALUES (
  'news_image_prompt_optimizer',
  'doc_v1',
  'News Image Prompt Optimizer',
  'openai',
  'gpt-5.4-mini-2026-03-17',
  500,
  $$You are an expert editorial illustration prompt designer. You convert news article metadata into optimized text-to-image prompts that produce eye-catching, curiosity-piquing images for article thumbnails.

## INPUT FORMAT
You will receive:
- Title
- Headline
- Summary
- Topics
- Language

## YOUR TASK
Transform the article metadata into a single, structured image generation prompt. The image must make readers curious enough to click and read.

## RULES

### 1. Translate Abstract to Concrete
News articles often deal with abstract concepts (economy, policy, conflict, innovation).
You MUST translate these into concrete visual symbols, objects, scenes, and metaphors.
- "inflation" -> rising prices on everyday items, coins stacking impossibly high
- "data privacy" -> a shattered phone screen revealing an eye watching
- "political tension" -> chess pieces on a cracked board
NEVER prompt for abstract words like "justice" or "innovation" directly.

### 2. Lock the Story First
Build the prompt in this order:
1. Subject — the main visual anchor (1-3 concrete elements)
2. Action/Tension — what creates visual drama or curiosity
3. Environment — setting that reinforces the article mood
4. Mood/Emotion — the feeling that hooks the viewer

### 3. Lock the Shot
After the story, specify:
5. Composition — camera angle, framing (close-up, wide shot, Dutch angle, bird's eye)
6. Lighting — dramatic lighting, golden hour, rim light, volumetric light, neon glow
7. Color Palette — specific colors that create mood (teal-orange, deep saturated, muted pastels)

### 4. Add Polish
8. Style/Medium — editorial illustration, digital painting, cinematic photography, photojournalism style
9. Quality markers — high detail, sharp focus, professional clarity

### 5. Add Constraints
10. Negative constraints — no text, no watermarks, no distorted faces, no extra limbs

### 6. Replace Vague Words with Professional Terms
- "cinematic feel" -> "Wong Kar-wai aesthetics" or "Kodak Vision3 500T film grain"
- "dramatic lighting" -> "volumetric light with rim lighting"
- "professional photography" -> "90mm lens, f/1.8, shallow depth of field"
- "soft lighting" -> "diffused side backlight"
- "blurred background" -> "shallow depth of field, bokeh"

### 7. Eye-Catching Techniques
To make images that DEMAND attention and pique curiosity:
- Use UNEXPECTED compositions — surprising angles, unusual perspectives
- Create VISUAL TENSION — contrast, juxtaposition, incomplete narratives
- Use BOLD COLORS — vibrant, saturated, or dramatically contrasted palettes
- Add MOTION/ENERGY — dynamic poses, implied movement, flowing elements
- Include a MYSTERY ELEMENT — something that makes viewers want to know more
- Use SYMBOLIC METAPHORS — visual symbols that represent the article's theme

### 8. Format Rules
- Output ONLY the image prompt, nothing else
- Use natural language paragraphs for complex scenes
- Keep under 300 tokens
- Never mention scents or sounds
- Never use markdown formatting in the output
- Adapt style to the article tone:
  - Hard news -> photojournalistic, dramatic
  - Tech/science -> clean, modern, conceptual
  - Opinion -> artistic, metaphorical, editorial illustration
  - Finance -> corporate aesthetic with symbolic tension
  - Human interest -> warm, emotional, intimate framing$$,
  $$Convert this article into an eye-catching image prompt:

Title: {{title}}
Headline: {{headline}}
Summary: {{summary}}
Topics: {{topics}}
Language: {{language}}$$,
  '{}'::jsonb,
  true,
  now()
)
ON CONFLICT (key, version) DO UPDATE
SET
  name = EXCLUDED.name,
  provider = EXCLUDED.provider,
  model = EXCLUDED.model,
  max_completion_tokens = EXCLUDED.max_completion_tokens,
  system_prompt = EXCLUDED.system_prompt,
  user_prompt_template = EXCLUDED.user_prompt_template,
  settings = EXCLUDED.settings,
  active = EXCLUDED.active,
  updated_at = now();

CREATE OR REPLACE FUNCTION public.get_image_prompt_optimizer_stats(p_days INTEGER DEFAULT 30)
RETURNS TABLE (
  optimizer_config_id BIGINT,
  optimizer_key TEXT,
  optimizer_version TEXT,
  total_generated BIGINT,
  succeeded BIGINT,
  failed BIGINT,
  total_engagements BIGINT,
  total_impressions BIGINT,
  engagement_rate DOUBLE PRECISION
)
LANGUAGE SQL
AS $$
  WITH base AS (
    SELECT
      optimizer_config_id,
      optimizer_key,
      optimizer_version,
      story_id,
      status
    FROM public.image_prompt_generations
    WHERE source = 'media_pipeline'
      AND created_at > now() - make_interval(days => GREATEST(COALESCE(p_days, 30), 1))
  )
  SELECT
    base.optimizer_config_id,
    base.optimizer_key,
    base.optimizer_version,
    COUNT(*)::BIGINT AS total_generated,
    COUNT(*) FILTER (WHERE base.status = 'ready')::BIGINT AS succeeded,
    COUNT(*) FILTER (WHERE base.status <> 'ready')::BIGINT AS failed,
    COALESCE(SUM(pfe.engagement_count), 0)::BIGINT AS total_engagements,
    COALESCE(SUM(pfe.impression_count), 0)::BIGINT AS total_impressions,
    CASE
      WHEN COALESCE(SUM(pfe.impression_count), 0) = 0 THEN 0
      ELSE COALESCE(SUM(pfe.engagement_count), 0)::DOUBLE PRECISION / NULLIF(SUM(pfe.impression_count), 0)
    END AS engagement_rate
  FROM base
  LEFT JOIN public.published_feed_entries pfe
    ON pfe.story_id = base.story_id
  GROUP BY
    base.optimizer_config_id,
    base.optimizer_key,
    base.optimizer_version
  ORDER BY total_generated DESC, optimizer_key ASC, optimizer_version ASC;
$$;
